### ISSUE TITLE
labels are overlapping

### ISSUE THREAD

**Issue by fireheadman** [custom-cards/dual-gauge-card#42]
Is there a way to have the labels not overlap?
![image](https://user-images.githubusercontent.com/19847195/98298193-d2e6b580-1f72-11eb-9618-3bcee3a68074.png)

![image](https://user-images.githubusercontent.com/19847195/98298297-032e5400-1f73-11eb-9003-b4cdccd84e3d.png)

Increasing card width to 500 does not help either
![image](https://user-images.githubusercontent.com/19847195/98298449-3cff5a80-1f73-11eb-975b-4f7c405e35ab.png)

```
type: 'custom:dual-gauge-card'
title: Current Consumption/Production
min: 0
max: 15000
outer:
  entity: sensor.envoyenvoy_current_energy_consumption
  unit: W
  colors:
    - color: var(--label-badge-blue)
inner:
  entity: sensor.envoyenvoy_current_energy_production
  unit: W
  colors:
    - color: var(--label-badge-green)
cardwidth: 500
```
