### ISSUE TITLE
Sensor name/info overlaps

### ISSUE THREAD

**Issue by JakeTheRabbit** [custom-cards/dual-gauge-card#71]
<img width="218" alt="image" src="https://github.com/custom-cards/dual-gauge-card/assets/123831499/7d4bce69-8f60-4cfc-94e3-26510214315b">

```
type: custom:dual-gauge-card
title: Outside
min: -20
max: 40
outer:
  entity: sensor.ruuvi_d_temperature
  label: Current
  unit: °C
inner:
  entity: sensor.ruuvi_d_humidity
  label: Target
  unit: °C
colors:
  - color: var(--label-badge-red)
    value: 27.5
  - color: var(--label-badge-green)
    value: 25
  - color: var(--label-badge-yellow)
    value: 18
  - color: var(--label-badge-blue)
    value: 0
  - color: var(--paper-blue-400)
    value: -40
precision: 0
```
